name: Compruebo el retrain

on:
  schedule:
    - cron: '0 0/2 * * *' #Ejecuto cada 2 horas 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Analizo el Repo
        uses: actions/checkout@v2 
    
      - name: Configuro Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7' 
      
      - name: Instalo los paquetes necesarios
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Ejecutar script de python 
        env:
          URI: ${{ secrets.URI }}
          TOKEN: ${{secrets.TOKEN}}
        run: python check_retrain.py
