name: actualizar-datos-bbdd

on:
  schedule:
    - cron: '0 0/6 * * *' #Ejecuto cada 6 horas 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Analizo el Repo
        uses: actions/checkout@v2 

      - name: Configuro Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7' 
          
      - name: Instalo los paquetes necesarios
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Ejecutar script de python 
        env: 
          URI: ${{ secrets.URI }}
        run: python update_real_data.py
